services:
  backend:
    build:
        context: ./backend
    image: todo_list:latest
    ports:
      - "3000:3000"
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3006:3006"
    depends_on:
      - backend
